# -*- mode: ruby -*-
# vi: set ft=ruby :
EXTERNAL_IP = "192.168.33.10"
KUBERNETES_VERSION = "1.21.0"
CRI_TOOLS_VERSION = "1.21.0"

required_plugins = %w(vagrant-vbguest)

required_plugins.each do |plugin|
  need_restart = false
  unless Vagrant.has_plugin? plugin
    system "vagrant plugin install #{plugin}"
    need_restart = true
  end
  exec "vagrant #{ARGV.join(' ')}" if need_restart
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/hirsute64"

  config.vm.define "ubuntu-rust"

  # if Vagrant.has_plugin?("vagrant-vbguest")
  #   # set auto_update to false, if you do NOT want to check the correct 
  #   # additions version when booting this machine
  #   config.vbguest.auto_update = false
    
  #   # # do NOT download the iso file from a webserver
  #   config.vbguest.no_remote = true
  #   config.vbguest.no_install = true
  # end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", type: "dhcp"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  #################################################################################################
  # Need this extra provision step with reset: true otherwise the vagrant user cant access docker #
  #################################################################################################
  config.vm.provision "shell", env: {"EXTERNAL_IP" => EXTERNAL_IP, "KUBERNETES_VERSION" => KUBERNETES_VERSION}, privileged: false, reset: true, inline: <<-SHELL
    #!/bin/bash

    # Update apt and get dependencies
    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y zip unzip curl git conntrack
    
    # Install docker (needed for minikube vm-driver none)
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg 2>/dev/null | sudo apt-key add -
    sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-compose
    # Add vagrant user to the docker group 
    sudo usermod -aG docker vagrant
  SHELL
  
  config.vm.provision "shell", env: {"EXTERNAL_IP" => EXTERNAL_IP, "KUBERNETES_VERSION" => KUBERNETES_VERSION}, privileged: false, inline: <<-SHELL
    #!/bin/bash
    groups vagrant
    echo "check if the vagrant user can access docker"
    docker ps

    sudo apt-get install -y rustc
    sudo snap install --classic rustup
    rustup default stable
    cd /vagrant/src
    rustc main.rs
    #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  SHELL
end
